import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#d6c953",
        "inverse-primary": "#7cd0ff",
        "on-primary-container": "#00455f",
        "tertiary-container": "#baae3b",
        "on-background": "#1a1c19",
        "on-surface-variant": "#3e484f",
        "secondary-container": "#fdaa3f",
        "surface-dim": "#dadad5",
        "on-primary-fixed": "#001e2c",
        "secondary-fixed": "#ffddba",
        surface: "#fafaf5",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8e3",
        "surface-bright": "#fafaf5",
        "inverse-surface": "#2f312e",
        "on-tertiary-fixed-variant": "#4e4800",
        "primary-fixed-dim": "#7cd0ff",
        "on-primary-fixed-variant": "#004c69",
        "error-container": "#ffdad6",
        "outline-variant": "#bec8d0",
        secondary: "#875200",
        primary: "#00668a",
        "on-secondary": "#ffffff",
        tertiary: "#686000",
        "on-secondary-fixed-variant": "#673d00",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb866",
        "surface-container-low": "#f4f4ef",
        "surface-container-highest": "#e3e3de",
        "surface-container": "#eeeee9",
        "tertiary-fixed": "#f3e56c",
        "on-secondary-container": "#6d4100",
        outline: "#6f7880",
        "on-tertiary-fixed": "#1f1c00",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary-container": "#474100",
        "primary-container": "#4fb6e9",
        "primary-fixed": "#c4e7ff",
        "on-error": "#ffffff",
        "on-surface": "#1a1c19",
        "surface-variant": "#e3e3de",
        "on-tertiary": "#ffffff",
        "surface-tint": "#00668a",
        background: "#fafaf5",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f1ec",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["'Baloo Bhaijaan 2'", "sans-serif"],
        body: ["'Cairo'", "sans-serif"],
        label: ["'Cairo'", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
