import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#dbeef0",
        "inverse-primary": "#ffffff",
        "on-primary-container": "#001f26",
        "tertiary-container": "#e6f6f8",
        "on-background": "#072127",
        "on-surface-variant": "#6b7074",
        "secondary-container": "#f0f7f8",
        "surface-dim": "#f7f9fa",
        "on-primary-fixed": "#003544",
        "secondary-fixed": "#bfe6ea",
        surface: "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#f3f7f8",
        "surface-bright": "#ffffff",
        "inverse-surface": "#0b1b1f",
        "on-tertiary-fixed-variant": "#0e2a2f",
        "primary-fixed-dim": "#cfecef",
        "on-primary-fixed-variant": "#0a2428",
        "error-container": "#ffebe9",
        "outline-variant": "#cbd5d8",
        secondary: "#006a7a",
        primary: "#00668a",
        "on-secondary": "#ffffff",
        "tertiary": "#00a5b0",
        "on-secondary-fixed-variant": "#05292d",
        "on-error-container": "#610000",
        "secondary-fixed-dim": "#d7eef1",
        "surface-container-low": "#fbfcfc",
        "surface-container-highest": "#f0f6f7",
        "surface-container": "#f8fafa",
        "tertiary-fixed": "#bfeef2",
        "on-secondary-container": "#003338",
        outline: "#e6eef0",
        "on-tertiary-fixed": "#003233",
        "on-secondary-fixed": "#002026",
        "on-tertiary-container": "#002a2d",
        "primary-container": "#e6f7fb",
        "primary-fixed": "#99e0e9",
        "on-error": "#b00020",
        "on-surface": "#072127",
        "surface-variant": "#eef3f4",
        "on-tertiary": "#00363a",
        "surface-tint": "#eaf7f9",
        background: "#f7fbfb",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#dbeff2",
        error: "#b00020",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Baloo Bhaijaan 2", "cursive"],
        body: ["Cairo", "sans-serif"],
        label: ["Cairo", "sans-serif"],
      },
    },
  },
  plugins: [forms],
};

export default config;
