# Generated by Django 5.2.13 on 2026-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prochatsession',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='prochatsession',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
