# Generated by Django 5.2.13 on 2026-04-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='release_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='firmware.releasegroup'),
        ),
    ]
