# Generated by Django 5.2.13 on 2026-04-25 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_hex', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{2,20}$', 'uid_hex must be 2..20 lowercase hex chars')])),
                ('title', models.CharField(max_length=120)),
                ('is_pro', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, default='', max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='audio/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('semsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='semsems.semsem')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('semsem', 'name')},
            },
        ),
    ]
