# Generated by Django 5.2.13 on 2026-04-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semsems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemsemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='semsem',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='semsems', to='semsems.semsemgroup'),
        ),
    ]
