# Generated by Django 5.2.13 on 2026-04-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_hex', models.CharField(max_length=20)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('total_play_ms', models.PositiveBigIntegerField(default=0)),
                ('last_played_unix', models.BigIntegerField(default=0)),
                ('pro_session_count', models.PositiveIntegerField(default=0)),
                ('pro_total_ms', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='devices.device')),
            ],
            options={
                'unique_together': {('device', 'uid_hex')},
            },
        ),
    ]
