# Generated by Django 5.2.13 on 2026-05-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUsageStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid_hex", models.CharField(max_length=20)),
                ("day", models.DateField()),
                ("play_count_delta", models.PositiveIntegerField(default=0)),
                ("play_ms_delta", models.PositiveBigIntegerField(default=0)),
                ("pro_session_count_delta", models.PositiveIntegerField(default=0)),
                ("pro_total_ms_delta", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_stats", to="devices.device")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "uid_hex", "day"),
                        name="stats_dailyusagestats_device_uid_day_uniq",
                    )
                ],
            },
        ),
    ]
